### ISSUE TITLE
jtag package on npm 

### ISSUE THREAD

**Issue by bhavincb** [bhavincb/jTag#1]
Hello Bhavin,

I have noticed, that you (probably) have published `jtag` package on NPM while ago.
I was wondering if you (or anybody else) are actively using this package or have other plans?
I wanted to publish JS package that implements [JTAG](https://en.wikipedia.org/wiki/JTAG) under `jtag` name:

Let me know in case is nobody actively using `jtag` package on NPM you could unpublish it.

Best regards,
Aliaksei Chapyzhenka

copied from: [https://github.com/bhavincb/nativescript-mediapicker/issues/1](https://github.com/bhavincb/nativescript-mediapicker/issues/1)

**Comment by bhavincb** [comment]
yes, indeed we are using this package actively in our projects. because of which unable to change it's name.

**Comment by drom** [comment]
Thank you for the prompt reply.
